### ISSUE TITLE
Recommend registering custom Taxonomies to appear in the REST API as well

### ISSUE THREAD

**Issue by rungta** [craftcms/wp-import#6]
https://github.com/craftcms/wp-import/blob/6a776dd5963c0e1c33c00ac0341bfb1c0e4161fa/README.md?plain=1#L54

Custom Taxonomies added via [`register_taxonomy()`](https://developer.wordpress.org/reference/functions/register_taxonomy/) may also need to set `'show_in_rest' => true`, similar to custom post types.

**Comment by brandonkelly** [comment]
Done, thanks for the suggestion!
