### ISSUE TITLE
`data['icon']` does not exist for PostType in WP 5.9 / 6.0

### ISSUE THREAD

**Issue by rungta** [craftcms/wp-import#7]
https://github.com/craftcms/wp-import/blob/6a776dd5963c0e1c33c00ac0341bfb1c0e4161fa/src/importers/PostType.php#L196

Not sure which version of WP starts exposing the icon via the `icon` field, but this line seems to be throwing an error at least on WP versions 5.9 and 6.0. Adding a fallback fixes this:

```php
$entryType->icon = $this->command->normalizeIcon($this->data['icon'] ?? 'default') ?? 'pen-nib';
```

Update: may have been [added to the API in 6.2](https://github.com/WP-API/docs/commit/ddf1381bcf8b5279354a2c6850ec40ce9c325f6d#diff-5e7be360892ed9a74638c05548e41f60eb4f8b6cb01e66e838d659415f70e4f3) as per the docs.

**Comment by brandonkelly** [comment]
Fixed, thanks for reporting!
