### ISSUE TITLE
Recommend enabling REST API support for ACF fields registered via PHP

### ISSUE THREAD

**Issue by rungta** [craftcms/wp-import#8]
https://github.com/craftcms/wp-import/blob/6a776dd5963c0e1c33c00ac0341bfb1c0e4161fa/README.md?plain=1#L59-L65

I couldn’t find this documented anywhere on the ACF site, but discovered the hard way that [ACF fields registered via PHP](https://www.advancedcustomfields.com/resources/register-fields-via-php/) don't automatically show up in the REST API and need to be opted-in by setting `'show_in_rest' => 1` in the `$field_group` parameter when calling the [`acf_add_local_field_group( $field_group )`](https://www.advancedcustomfields.com/resources/register-fields-via-php/#basic) function.

**Comment by brandonkelly** [comment]
Had no idea that `acf_add_local_field_group()` existed. Thanks!
