### ISSUE TITLE
Support for `core/pullquote` block type

### ISSUE THREAD

**Issue by KevinBodi** [craftcms/wp-import#9]
### Description

The core [pullquote block](https://wordpress.com/support/wordpress-editor/blocks/pullquote-block/) type from Wordpress is not supported.
I created this issue to see if there's any demand for this from others.

### Steps to reproduce

1. Run `craft wp-import` on a site that uses the `core/pullquote` block type
2. Get these import errors: 
```
Error: Unknown block type: core/pullquote
Block data:
{
    "blockName": "core/pullquote",
    "attrs": [],
    "innerBlocks": [],
    "innerHTML": "\n<figure class=\"wp-block-pullquote\"><blockquote><p>\"<em>This changes everything</em>\"</p></blockquote></figure>\n",
    "innerContent": [
        "\n<figure class=\"wp-block-pullquote\"><blockquote><p>\"<em>This changes everything</em>\"</p></blockquote></figure>\n"
    ]
}
```

### Additional info

- Craft version: 5.5.0
- PHP version: 8.2
- Database driver & version: mysql 8.0
- Wordpress version: 6.7.1

**Comment by brandonkelly** [comment]
Added!
